# Generated by Django 5.2.7 on 2025-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='original_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Оригинальный email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='original_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Оригинальный username'),
        ),
    ]
