# Generated by Django 5.2.7 on 2025-12-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_original_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='original_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='original_username',
        ),
    ]
